# Generated by Django 2.1.7 on 2019-06-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloqueadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
