# Generated by Django 2.1.7 on 2019-06-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloqueadores', '0002_auto_20190617_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='espectro',
            name='samp_rate',
            field=models.FloatField(default=1000000.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.CharField(max_length=20),
        ),
    ]
