# Generated by Django 2.1.7 on 2019-06-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloqueadores', '0003_auto_20190620_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='espectro',
            name='fft_size',
            field=models.FloatField(default=4096),
            preserve_default=False,
        ),
    ]
