# Generated by Django 2.1.7 on 2019-06-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloqueadores', '0004_espectro_fft_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espectro',
            name='fft_size',
            field=models.IntegerField(),
        ),
    ]
