# Generated by Django 2.1.7 on 2019-06-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloqueadores', '0005_auto_20190620_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.CharField(max_length=50),
        ),
    ]
