# Generated by Django 2.1.7 on 2019-06-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloqueadores', '0006_auto_20190620_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espectro',
            old_name='espectro_IQ',
            new_name='espectro_iq',
        ),
    ]
