# Generated by Django 2.1.7 on 2019-08-07 15:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_colegio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50, unique=True)),
                ('nombre_rector', models.CharField(max_length=50)),
                ('correo_rector', models.EmailField(max_length=254)),
                ('direccion_colegio', models.CharField(max_length=50)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Flujo_agua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Humedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_kit', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=200, null=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Colegio')),
            ],
        ),
        migrations.CreateModel(
            name='KitNariz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('kit_monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit')),
            ],
        ),
        migrations.CreateModel(
            name='PH_agua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('kit_monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit')),
            ],
        ),
        migrations.CreateModel(
            name='PresionAtmosferica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField()),
                ('kit_monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit')),
            ],
        ),
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=25)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Colegio')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit')),
            ],
            options={
                'verbose_name': 'Semillero',
                'db_table': '',
                'managed': True,
                'verbose_name_plural': 'Semilleros',
            },
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField()),
                ('kit_monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit')),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura_agua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('kit_monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit')),
            ],
        ),
        migrations.CreateModel(
            name='Turbidez_agua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('kit_monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion_lectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta_ubicacion', models.CharField(max_length=100)),
                ('tipo_experimento', models.CharField(max_length=50)),
                ('semillero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Semillero')),
            ],
            options={
                'db_table': '',
                'ordering': ['etiqueta_ubicacion'],
                'managed': True,
                'verbose_name_plural': 'Ubicacion_lecturas',
                'verbose_name': 'Ubicacion_lectura',
            },
        ),
        migrations.AddField(
            model_name='turbidez_agua',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
        ),
        migrations.AddField(
            model_name='temperatura_agua',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
        ),
        migrations.AddField(
            model_name='presionatmosferica',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
        ),
        migrations.AddField(
            model_name='ph_agua',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
        ),
        migrations.AddField(
            model_name='kitnariz',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
        ),
        migrations.AddField(
            model_name='humedad',
            name='kit_monitoreo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit'),
        ),
        migrations.AddField(
            model_name='humedad',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
        ),
        migrations.AddField(
            model_name='flujo_agua',
            name='kit_monitoreo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit'),
        ),
        migrations.AddField(
            model_name='flujo_agua',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
        ),
    ]
