# Generated by Django 2.1.7 on 2019-05-31 08:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitNariz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicion', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
            ],
        ),
    ]
