# Generated by Django 2.1.7 on 2019-07-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0006_flujo_agua_ph_agua_temperatura_agua_turbidez_agua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion_lectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta_ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ubicacion_lectura',
                'verbose_name_plural': 'Ubicacion_lecturas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='colegio',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='ubicacion_kit',
        ),
    ]
