# Generated by Django 2.1.7 on 2019-07-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0007_auto_20190710_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensores',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
            preserve_default=False,
        ),
    ]
