# Generated by Django 2.1.7 on 2019-07-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0009_auto_20190710_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitnariz',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit'),
        ),
    ]
