# Generated by Django 2.1.7 on 2019-07-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0010_auto_20190710_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensores',
            name='nombre_sensor',
        ),
    ]
