# Generated by Django 2.1.7 on 2019-07-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0011_remove_sensores_nombre_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensores',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='flujo_agua',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humedad',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitnariz',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ph_agua',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presionatmosferica',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatura_agua',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turbidez_agua',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_praes.Ubicacion_lectura'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sensores',
        ),
    ]
