# Generated by Django 2.1.7 on 2019-07-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0012_auto_20190724_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitnariz',
            name='asociacion',
        ),
        migrations.DeleteModel(
            name='Asociacion',
        ),
    ]
