# Generated by Django 2.1.7 on 2019-07-25 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0013_auto_20190725_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitnariz',
            old_name='kit',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='kitnariz',
            old_name='medicion',
            new_name='valor',
        ),
        migrations.AddField(
            model_name='kitnariz',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
