# Generated by Django 2.1.7 on 2019-07-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0014_auto_20190725_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flujo_agua',
            old_name='sensor',
            new_name='kit_monitoreo',
        ),
        migrations.RenameField(
            model_name='humedad',
            old_name='sensor',
            new_name='kit_monitoreo',
        ),
        migrations.RenameField(
            model_name='kitnariz',
            old_name='sensor',
            new_name='kit_monitoreo',
        ),
        migrations.RenameField(
            model_name='ph_agua',
            old_name='sensor',
            new_name='kit_monitoreo',
        ),
        migrations.RenameField(
            model_name='presionatmosferica',
            old_name='sensor',
            new_name='kit_monitoreo',
        ),
        migrations.RenameField(
            model_name='temperatura',
            old_name='sensor',
            new_name='kit_monitoreo',
        ),
        migrations.RenameField(
            model_name='temperatura_agua',
            old_name='sensor',
            new_name='kit_monitoreo',
        ),
        migrations.RenameField(
            model_name='turbidez_agua',
            old_name='sensor',
            new_name='kit_monitoreo',
        ),
    ]
