# Generated by Django 2.1.7 on 2019-08-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0015_auto_20190725_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion_lectura',
            name='tipo_experimento',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
