# Generated by Django 2.1.7 on 2019-08-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0016_ubicacion_lectura_tipo_experimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion_lectura',
            name='semillero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_praes.Semillero'),
            preserve_default=False,
        ),
    ]
