# Generated by Django 2.1.7 on 2019-08-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0017_ubicacion_lectura_semillero'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
