# Generated by Django 2.1.7 on 2019-08-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0018_semillero_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrantes',
            name='semillero',
        ),
        migrations.AlterModelOptions(
            name='semillero',
            options={'managed': True, 'verbose_name': 'Semillero', 'verbose_name_plural': 'Semilleros'},
        ),
        migrations.AlterModelTable(
            name='semillero',
            table='',
        ),
        migrations.DeleteModel(
            name='Integrantes',
        ),
    ]
