# Generated by Django 2.1.7 on 2020-08-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SENSORES4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.FloatField()),
                ('s2', models.FloatField()),
                ('s3', models.FloatField()),
                ('s4', models.FloatField()),
            ],
            options={
                'verbose_name': 'SENSORES4',
                'verbose_name_plural': 'SENSORES4s',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
