# Generated by Django 2.1.7 on 2019-06-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'ordering': ['city'], 'verbose_name': 'Geolocation', 'verbose_name_plural': 'Geolocations'},
        ),
    ]
