# Generated by Django 2.1.7 on 2019-08-10 14:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
                ('spo2', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
                ('estado_bateria', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lecturas',
                'verbose_name_plural': 'Lecturass',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
