# Generated by Django 2.1.7 on 2019-06-07 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piscicultura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voltajebateria',
            name='pozo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='piscicultura.Pozo'),
            preserve_default=False,
        ),
    ]
