# Generated by Django 2.1.7 on 2019-04-24 14:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntennaCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('height_Type', models.CharField(choices=[('AGL', 'Above Ground Level'), ('AMSL', 'AMSL: Above Mean Sea Level')], default='AGL', max_length=50)),
                ('antenna_direction', models.CharField(blank=True, max_length=20)),
                ('antenna_radiation_pattern', models.CharField(blank=True, max_length=15)),
                ('antenna_gain', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_Number', models.CharField(max_length=25)),
                ('manufacturer_Id', models.CharField(max_length=25)),
                ('model_Id', models.CharField(max_length=25)),
                ('ruleset_Ids', django.contrib.postgres.fields.jsonb.JSONField()),
                ('anttenna_characteristics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.AntennaCharacteristics')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('device_descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.DeviceDescriptor')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.BooleanField()),
                ('reason', models.CharField(max_length=150)),
                ('deviceDesc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.DeviceDescriptor')),
            ],
        ),
        migrations.CreateModel(
            name='Ellipse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semi_Major_Axis', models.FloatField()),
                ('semi_Minor_Axis', models.FloatField()),
                ('orientation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_Time', models.DateTimeField()),
                ('stop_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FrequencyRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_Hz', models.FloatField()),
                ('stop_Hz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.IntegerField(default=95)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.Ellipse')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RulsetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=50)),
                ('rulsetId', models.CharField(max_length=50)),
                ('max_Location_Change', models.FloatField(blank=True)),
                ('max_Polling_Secs', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_Bw_Hz', models.FloatField()),
                ('profiles', django.contrib.postgres.fields.jsonb.JSONField()),
                ('geolocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.Geolocation')),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumProfilePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hz', models.FloatField()),
                ('dbm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.EventTime')),
                ('spectrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.Spectrum')),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_Ranges', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
                ('needs_Spectrum_Report', models.BooleanField()),
                ('max_Total_BwHz', models.FloatField(blank=True)),
                ('max_Contiguous_Bw_Hz', models.FloatField(blank=True)),
                ('geolocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.Geolocation')),
                ('rulset_Info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.RulsetInfo')),
                ('spectrum_Schedules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.SpectrumSchedule')),
                ('time_Range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.EventTime')),
            ],
        ),
        migrations.AddField(
            model_name='spectrumprofile',
            name='list1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.SpectrumProfilePoint'),
        ),
        migrations.AddField(
            model_name='spectrumprofile',
            name='rulsetinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.RulsetInfo'),
        ),
        migrations.AddField(
            model_name='ellipse',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.Point'),
        ),
        migrations.AddField(
            model_name='devicedescriptor',
            name='device_capabilities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.FrequencyRange'),
        ),
        migrations.AddField(
            model_name='devicedescriptor',
            name='geolocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.Geolocation'),
        ),
    ]
