# Generated by Django 2.1.7 on 2019-05-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0002_auto_20190508_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('channels', models.IntegerField(primary_key=True, serialize=False)),
                ('frequency', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='channels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paws.Frequency'),
        ),
    ]
