# Generated by Django 2.1.7 on 2020-08-07 11:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(max_length=200, null=True, upload_to='videos/', verbose_name='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AlbumImagenes',
                'verbose_name_plural': 'AlbumImageness',
                'db_table': '',
                'ordering': ['fecha'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bandas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banda', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10)),
                ('frecuencia_inicial', models.FloatField()),
                ('frecuencia_final', models.FloatField()),
            ],
            options={
                'verbose_name': 'Bandas',
                'verbose_name_plural': 'Bandass',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CaracteristicasAntena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('rango_frecuencias', models.CharField(max_length=50)),
                ('polarizacion', models.CharField(blank=True, max_length=50)),
                ('conector', models.CharField(blank=True, max_length=50)),
                ('imagen', models.ImageField(upload_to='album/antenas')),
                ('vswr', models.ImageField(upload_to='album/vswr')),
                ('caracterizacion_csv', models.FileField(upload_to='caracterizacion')),
            ],
            options={
                'verbose_name': 'CaracteristicasAntena',
                'verbose_name_plural': 'CaracteristicasAntenas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CaracteristicasEspectro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_v', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
                ('min_v', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
                ('energia', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
            ],
            options={
                'verbose_name': 'CaracteristicasEspectro',
                'verbose_name_plural': 'CaracteristicasEspectros',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CaracteristicasEstacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=50)),
                ('variable', models.CharField(max_length=50)),
                ('rango', models.CharField(max_length=50)),
                ('resolucion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CaracteristicasEstacion',
                'verbose_name_plural': 'CaracteristicasEstacions',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Espectro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('espectro', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
                ('frec_muestreo', models.IntegerField()),
                ('nfft', models.IntegerField()),
                ('frec_central', models.FloatField()),
                ('duracion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EstacionAmbiental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField()),
                ('humedad_relativa', models.FloatField()),
                ('presion_atomosferica', models.FloatField()),
                ('radiacion_solar', models.FloatField()),
                ('vel_viento', models.FloatField()),
                ('dir_viento', models.CharField(max_length=50)),
                ('precipitacion', models.FloatField()),
            ],
            options={
                'verbose_name': 'EstacionAmbiental',
                'verbose_name_plural': 'EstacionAmbientals',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('frecuencia', models.FloatField()),
                ('azimut', models.FloatField()),
                ('elevacion', models.FloatField()),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estadocamara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camara', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estadocamara',
                'verbose_name_plural': 'Estadocamaras',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estadoestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estadoestacion',
                'verbose_name_plural': 'Estadoestacions',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoPosicionAntena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azimut', models.IntegerField()),
                ('elevacion', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'EstadoPosicionAntena',
                'verbose_name_plural': 'EstadoPosicionAntenas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PosicionAntena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azimut', models.FloatField()),
                ('elevacion', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('antena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioastronomia.CaracteristicasAntena')),
            ],
        ),
        migrations.CreateModel(
            name='RBW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_muestreo', models.IntegerField()),
                ('nfft', models.IntegerField()),
                ('rbw', models.FloatField()),
            ],
            options={
                'verbose_name': 'RBW',
                'verbose_name_plural': 'RBWs',
                'db_table': '',
                'ordering': ['rbw'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegionCampana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('latitud', models.CharField(blank=True, max_length=50)),
                ('longitud', models.CharField(blank=True, max_length=50)),
                ('imagen', models.ImageField(blank=True, upload_to='album/regiones')),
            ],
            options={
                'verbose_name': 'RegionCampana',
                'verbose_name_plural': 'RegionCampanas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=200)),
                ('frecuencia_inicial', models.FloatField()),
                ('frecuencia_final', models.FloatField()),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioastronomia.Bandas')),
            ],
            options={
                'verbose_name': 'Servicios',
                'verbose_name_plural': 'Servicioss',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='posicionantena',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioastronomia.RegionCampana'),
        ),
        migrations.AddField(
            model_name='estacionambiental',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioastronomia.RegionCampana'),
        ),
        migrations.AddField(
            model_name='espectro',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioastronomia.RegionCampana'),
        ),
        migrations.AddField(
            model_name='caracteristicasespectro',
            name='espectro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioastronomia.Espectro'),
        ),
        migrations.AddField(
            model_name='albumimagenes',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioastronomia.RegionCampana'),
        ),
    ]
