# Generated by Django 2.1.7 on 2019-08-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicionantena',
            name='antena',
        ),
        migrations.DeleteModel(
            name='CaracteristicasAntena',
        ),
    ]
