# Generated by Django 2.1.7 on 2019-07-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimagenes',
            name='imagen',
            field=models.FileField(max_length=200, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
