# Generated by Django 2.1.7 on 2019-08-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristicasespectro',
            old_name='energia',
            new_name='energia1',
        ),
    ]
