# Generated by Django 2.1.7 on 2020-08-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumVideosPhantom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(max_length=200, null=True, upload_to='videos/phantom/', verbose_name='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioastronomia.RegionCampana')),
            ],
            options={
                'verbose_name': 'AlbumVideosPhantom',
                'verbose_name_plural': 'AlbumVideosPhantom',
                'db_table': '',
                'ordering': ['fecha'],
                'managed': True,
            },
        ),
    ]
