# Generated by Django 2.1.7 on 2019-08-07 18:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0002_auto_20190807_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasAntena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_x', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
                ('area_efec', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
                ('directividad_antena', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
                ('referencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '',
                'verbose_name': 'CaracteristicasAntena',
                'verbose_name_plural': 'CaracteristicasAntenas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='posicionantena',
            name='antena',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radioastronomia.CaracteristicasAntena'),
            preserve_default=False,
        ),
    ]
