# Generated by Django 2.1.7 on 2019-08-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0003_auto_20190801_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='frecuencia',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
