# Generated by Django 2.1.7 on 2019-08-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0004_rbw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristicasantena',
            name='area_efec',
        ),
        migrations.RemoveField(
            model_name='caracteristicasantena',
            name='directividad_antena',
        ),
        migrations.RemoveField(
            model_name='caracteristicasantena',
            name='s_x',
        ),
        migrations.AddField(
            model_name='caracteristicasantena',
            name='conector',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicasantena',
            name='directividad',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristicasantena',
            name='imagen',
            field=models.ImageField(default='', upload_to='album/antenas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristicasantena',
            name='polarizacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicasantena',
            name='rango_frecuencias',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristicasantena',
            name='vswr',
            field=models.ImageField(default='', upload_to='album/vswr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regioncampana',
            name='latitud',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='regioncampana',
            name='longitud',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
