# Generated by Django 2.1.7 on 2019-08-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0006_auto_20190813_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioncampana',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
