# Generated by Django 2.1.7 on 2019-08-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0008_auto_20190813_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicasantena',
            name='vswr',
            field=models.ImageField(upload_to='album/vswr'),
        ),
    ]
