# Generated by Django 2.1.7 on 2019-08-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0009_auto_20190813_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='azimut',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estado',
            name='elevacion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
