# Generated by Django 2.1.7 on 2019-09-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0010_auto_20190822_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banda', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10)),
                ('frecuencia_inicial', models.FloatField()),
                ('frecuencia_final', models.FloatField()),
            ],
            options={
                'verbose_name': 'Bandas',
                'verbose_name_plural': 'Bandass',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=200)),
                ('frecuencia_inicial', models.FloatField()),
                ('frecuencia_final', models.FloatField()),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioastronomia.Bandas')),
            ],
            options={
                'verbose_name': 'Servicios',
                'verbose_name_plural': 'Servicioss',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
