# Generated by Django 2.1.7 on 2019-09-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0013_estacionambiental_precipitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionambiental',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
