# Generated by Django 2.1.7 on 2019-09-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0014_auto_20190924_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionambiental',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
