# Generated by Django 2.1.7 on 2019-09-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0015_auto_20190924_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='camara',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estado',
            name='estacion',
            field=models.BooleanField(default=False),
        ),
    ]
