# Generated by Django 2.1.7 on 2019-09-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0016_auto_20190927_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='camara',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='estacion',
        ),
    ]
