# Generated by Django 2.1.7 on 2019-10-30 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0018_estadocamara_estadoestacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumimagenes',
            options={'managed': True, 'ordering': ['-fecha'], 'verbose_name': 'AlbumImagenes', 'verbose_name_plural': 'AlbumImageness'},
        ),
        migrations.AddField(
            model_name='caracteristicasantena',
            name='perdidas_vector',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], encoder=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristicasantena',
            name='vswr_vector',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], encoder=''),
            preserve_default=False,
        ),
    ]
