# Generated by Django 2.1.7 on 2019-10-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0020_auto_20191030_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPosicionAntena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azimut', models.IntegerField()),
                ('elevacion', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'EstadoPosicionAntena',
                'verbose_name_plural': 'EstadoPosicionAntenas',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
