# Generated by Django 2.1.7 on 2019-11-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioastronomia', '0022_remove_caracteristicasantena_directividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumimagenes',
            options={'managed': True, 'ordering': ['fecha'], 'verbose_name': 'AlbumImagenes', 'verbose_name_plural': 'AlbumImageness'},
        ),
    ]
